{
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.21.0/atomicfu-0.21.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-macosarm64-0.21.0.klib",
          "size": 47246,
          "sha512": "eb9451a7b1912aac592a9535139f994593fd55452919231cd7edda5ffa07fdbf706abbafd5dcec0d2f7e9a1b5f19cac045328a54996c1a47b66e211f1fc05f15",
          "sha256": "f9cc52e7fbf91e6cca6d0995e2b4cd23bc25b70a580185e99c0ba2f074bf9dce",
          "sha1": "c9c72d4eed96e0c2543147e317201f96664b57e8",
          "md5": "37453e7318cd93283ee14a26ffa4ee49"
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-macosarm64-0.21.0-cinterop-interop.klib",
          "size": 7873,
          "sha512": "ebf58b4901de617b3229c8fe9b829e2ca21b0d03c11d4f93bd99b3d82d8c3df6b0e513fd40dfd15fcfaaf2c89df4ff57922069912c0ea78961dd579db79892a3",
          "sha256": "c6f32c6573e1d379ae8a86106808a74e52801d5dfe3e4524e89f79f9946c4677",
          "sha1": "a5a12fd27d2118ce326aefe27aebe65decdc6a56",
          "md5": "58d70d0e5dbc661e985ef3e9c6ec6d87"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "atomicfu-macosarm64-0.21.0-sources.jar",
          "url": "atomicfu-macosarm64-0.21.0-sources.jar",
          "size": 10264,
          "sha512": "fe45037b7571dbeac91f1c500658595bddf0e7afb9ac107513c75407745c1f0024b2a0152bf90e5632bb92bf94455c14e8c1e79186639885aa792325c42a78eb",
          "sha256": "d5fd78cd26c3d821721b7f6315701379d92ef58d6ae1f4020c810b4774b43712",
          "sha1": "2ade7383dbdc47c9f185ea5e7219410ce2ad7c3e",
          "md5": "d1baa4a4b2a23a77ccac36a151040326"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "atomicfu-macosarm64-0.21.0-metadata.jar",
          "url": "atomicfu-macosarm64-0.21.0-metadata.jar",
          "size": 261,
          "sha512": "18d895c8a92fe015f337de5796b10d206dac3e6696291711bb6f2e0e46cecaa16ffdeba7e516b7d9c75edab712c46f96a7ff58dfe45066fa3beddc3088c5ffb5",
          "sha256": "42a418d91fe1f0f827d325777e32b770114fbc5da808760615292ad768232bc6",
          "sha1": "51baa92e0001e6d37175f5739ec84406baa2391a",
          "md5": "ec828395e8a76c4692b195a41a496d09"
        }
      ]
    }
  ]
}
