{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.dokka",
    "module": "dokka-core",
    "version": "1.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "dokka-core-1.9.10.jar",
          "url": "dokka-core-1.9.10.jar",
          "size": 813290,
          "sha512": "129d12f646a9216d51a07e1ec0589a7c90710473cefbc66c9778ea0ef5ff95a68470d417629d0163380ccb145d0ec9d9a5cc6bcd2ad943a9ac1fc2cf83059116",
          "sha256": "6325b68bc351441dcd852a42d92181bbeb6b09bbec6e0a02ad5b8e3122a733df",
          "sha1": "27d25e594723dcad15427bc00014770bc7cd4de7",
          "md5": "250781ca6ece5ad02ac05d93062567cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7.1"
          },
          "reason": "CVE-2022-42003"
        }
      ],
      "files": [
        {
          "name": "dokka-core-1.9.10.jar",
          "url": "dokka-core-1.9.10.jar",
          "size": 813290,
          "sha512": "129d12f646a9216d51a07e1ec0589a7c90710473cefbc66c9778ea0ef5ff95a68470d417629d0163380ccb145d0ec9d9a5cc6bcd2ad943a9ac1fc2cf83059116",
          "sha256": "6325b68bc351441dcd852a42d92181bbeb6b09bbec6e0a02ad5b8e3122a733df",
          "sha1": "27d25e594723dcad15427bc00014770bc7cd4de7",
          "md5": "250781ca6ece5ad02ac05d93062567cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dokka-core-1.9.10-sources.jar",
          "url": "dokka-core-1.9.10-sources.jar",
          "size": 57826,
          "sha512": "0393035fc5ac4b7a5fc16aa3b4709e9e931b5d959e3a0050908fae01f09a5a6c833889e23bb50aa82493402938a2f914348395c2052142bf0caeba6f59a3866d",
          "sha256": "158c98908d4ebeeddc4aae21d6288bf1068e4bb9ca3e3d0b759fd7544344f457",
          "sha1": "d3615fce2aafaab262f86fb2b308398314fcfc06",
          "md5": "2f920d209d8b3c86c55aab81fe2ee5b7"
        },
        {
          "name": "dokka-core-1.9.10-sources.jar",
          "url": "dokka-core-1.9.10-sources.jar",
          "size": 57826,
          "sha512": "0393035fc5ac4b7a5fc16aa3b4709e9e931b5d959e3a0050908fae01f09a5a6c833889e23bb50aa82493402938a2f914348395c2052142bf0caeba6f59a3866d",
          "sha256": "158c98908d4ebeeddc4aae21d6288bf1068e4bb9ca3e3d0b759fd7544344f457",
          "sha1": "d3615fce2aafaab262f86fb2b308398314fcfc06",
          "md5": "2f920d209d8b3c86c55aab81fe2ee5b7"
        }
      ]
    }
  ]
}
