on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu', 'macos', 'windows' ]
    runs-on: '${{ matrix.os }}-latest'
    steps:
      - uses: actions/checkout@v4
      - id: parameters
        shell: bash
        run: |
          OS="${{matrix.os}}"
          case($OS) in
            "ubuntu")
              echo "arch=x86" >> $GITHUB_OUTPUT
              echo "profile=jvm,js,linux,wasm-js" >> $GITHUB_OUTPUT
              ;;
            "windows")
              echo "arch=x86" >> $GITHUB_OUTPUT
              echo "profile=mingw" >> $GITHUB_OUTPUT
              ;;
            "macos"
              echo "arch=arm64" >> $GITHUB_OUTPUT
              echo "profile=macos" >> $GITHUB_OUTPUT
              ;;
            default
              echo "Unable to determine arch from $OS"
              exit 1
              ;;
          esac
      - name: Set up JDK 11 for ${{ needs.build.parameters.outputs.arch }}
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: ${{ needs.build.parameters.outputs.arch }}
      - name: 'Build'
        shell: bash
        run: |
          echo "::info ::Build profile=${{ needs.build.parameters.outputs.profile }} on ${{ needs.build.parameters.outputs.arch }}"
          ./gradlew build -PbuildProfile=${{ needs.build.parameters.outputs.profile }}


